version: 1
default_environment: extract
project_id: 20ab51bb-9080-43d6-9faf-aaf733d164a0
environments:
  - name: extract
    config:
      plugins:
        extractors:
          - name: tap-csv
            config:
              files:
                - entity: public-order_details
                  path: ./extract/order_details.csv
                  keys: [order_id, product_id]
  - name: load
    config:
      plugins:
        extractors:
          - name: tap-csv
            config:
              files:
                - entity: public-order_details
                  path: ./output/source=csv/extracted_at=${EXTRACTED_AT}/table=public-order_details/
                  keys: [order_id, product_id]
                - entity: public-categories
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-categories/
                  keys: [category_id]
                - entity: public-customers
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-customers/
                  keys: [customer_id]
                - entity: public-employee_territories
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-employee_territories/
                  keys: [employee_id, territory_id]
                - entity: public-employees
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-employees/
                  keys: [employee_id]
                - entity: public-orders
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-orders/
                  keys: [order_id]
                - entity: public-products
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-products/
                  keys: [product_id]
                - entity: public-region
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-region/
                  keys: [region_id]
                - entity: public-shippers
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-shippers/
                  keys: [shipper_id]
                - entity: public-suppliers
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-suppliers/
                  keys: [supplier_id]
                - entity: public-territories
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-territories/
                  keys: [territory_id]
                - entity: public-us_states
                  path: ./output/source=postgres/extracted_at=${EXTRACTED_AT}/table=public-us_states/
                  keys: [state_id]
plugins:
  extractors:
    - name: tap-csv
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    - name: tap-postgres
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
      settings:
        - name: filter_schemas
          value: [public] # Substitua por esquemas que você deseja incluir
      config:
        host: localhost
        port: 5432
        user: northwind_user
        password: thewindisblowing
        database: northwind
      select:
        - "*.*"
  loaders:
    - name: target-postgres
      variant: meltanolabs
      pip_url: meltanolabs-target-postgres
      config:
        host: localhost
        port: 5433
        user: northwind_user
        password: thewindisblowing
        database: northwind-replication
        default_target_schema: ${SCHEMA}
    - name: target-csv
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/target-csv.git
      config:
        destination_path: ./output/source=${SOURCE}
        file_naming_scheme: extracted_at=${DATESTAMP}/table={stream_name}/{timestamp}.csv
  utilities:
    - name: airflow
      variant: apache
      pip_url:
        git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
        --constraint
        https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
jobs:
  - name: extract_csv
    tasks:
      - tap-csv target-csv
  - name: extract_postgres
    tasks:
      - tap-postgres target-csv
  - name: load_to_postgres
    tasks:
      - tap-csv target-postgres
